#!/bin/bash
#$ -N bqsr
#$ -ckpt restart
#$ -q som,pub64,free64,asom
#$ -pe make 64
#$ -t 1-178


#############
## Docstring
#############

## before running this script
## make and move to this directory 
## /dfs3/som/dalawson/drb/deepcelllineage/mitolin/data/gen/nguyen_nc_2018/ \
    ## 20190911-bqsr-DRB/erroroutput/
## run this script from this ^ directory
## so e & o files get deposited there

## to run a script on hpc use `qsub path/to/filename.sh`
    ## `qsub /dfs3/som/dalawson/drb/deepcelllineage/mitolin/src/gatkpp-4-bqsr-v0.1.0.sh`
## to check on the script's status: `qstat -u dalawson`
## to stop a submitted project by job-ID number: `qdel job-ID-number`


################################################
## load modules, create variables & directories
################################################

## add packages to PATH
module load java/1.8.0.111          # language of gatk & picard-tools
module load gatk/4.1.3.0            # includes picard tools
# module load samtools/1.9            # view (filter/convert) sort index

# create path variables to access data 
path2datadir='/dfs3/som/dalawson/drb/deepcelllineage/mitolin/data/'
# path to bams generated by gatkpp-3-markdup*.sh
path2bams=${path2datadir}'gen/nguyen_nc_2018/20190909-markdups-DRB/ind1/genomic/dupsmarked/'
# the path below has list: dupsmarkedlist.txt
path2list=${path2bams}

# create paths to deposit data
path2genomic=${path2datadir}'gen/nguyen_nc_2018/20190911-bqsr-DRB/genomic/'
path2baserecaltables=${path2genomic}'baserecaltables/'

## make directories for each 'deposit data' path above
mkdir $path2genomic
mkdir $path2baserecaltables

## create variables for list of bam files
dupsmarkedlist=${path2list}'dupsmarkedlist.txt'

## create a name variable
## note this name has '.bam' extension included
## e.g. i1-lib001-A01.bam
namewext=`head -n $SGE_TASK_ID $dupsmarkedlist | tail -n 1 | cut -f1`

## remove ext from name
## e.g. name=i1-lib001-A01
name=${namewext%'.bam'}


#############################
## gatk pre-processing con't
#############################


## generate baserecaltables using BaseRecalibrator
    ## https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_hellbender_tools_walkers_bqsr_BaseRecalibrator.php
    ## generates a report file with tables

gatk BaseRecalibrator \
   -I $path2bams$namewext \
   -R $path2datadir'ref/broad/bundles/b37/human_g1k_v37.fasta' \
   --known-sites $path2datadir'ref/broad/bundles/b37/dbsnp_138.b37.vcf' \
   --known-sites $path2datadir'ref/broad/bundles/b37/Mills_and_1000G_gold_standard.indels.b37.vcf' \
   --known-sites $path2datadir'ref/broad/bundles/b37/1000G_phase1.indels.b37.vcf' \
   -O $path2baserecaltables$name'.table'


## Next run gatkpp-5-applybqsr-v0.1.0.sh


