#!/bin/bash
#$ -N analcov
#$ -ckpt restart
#$ -q som,pub64,free64,asom
#$ -pe make 64
#$ -t 2-3


#############
## Docstring
#############

## before running this script
## make and move to this directory 
## /dfs3/som/dalawson/drb/deepcelllineage/mitolin/data/gen/nguyen_nc_2018/ \
    ## 20190911-bqsr-DRB/erroroutput/
## run this script from this ^ directory
## so e & o files get deposited there

## to run a script on hpc use `qsub path/to/filename.sh`
    ## `qsub /dfs3/som/dalawson/drb/deepcelllineage/mitolin/src/gatkpp-6-analcov-v0.1.0.sh`
## to check on the script's status: `qstat -u dalawson`
## to stop a submitted project by job-ID number: `qdel job-ID-number`


################################################
## load modules, create variables & directories
################################################

## add packages to PATH
module load java/1.8.0.111          # language of gatk & picard-tools
module load gatk/4.1.3.0            # includes picard tools
# module load samtools/1.9            # view (filter/convert) sort index

# create path variables to access data 
path2datadir='/dfs3/som/dalawson/drb/deepcelllineage/mitolin/data/'
# path to tables generated by gatkpp-4-baserecal*.sh
path2tables=${path2datadir}'gen/nguyen_nc_2018/20190911-bqsr-DRB/genomic/baserecaltables/'
# the path below has list: baserecaltablelist.txt
path2list=${path2tables}

# create path variables (for data deposit)
path2genomic=${path2datadir}'gen/nguyen_nc_2018/20190911-bqsr-DRB/genomic/'
path2analcovs=${path2genomic}'analcov/'

## make directories for each path to a directory that doesn't yet exist (in list above above)
mkdir $path2analcovs

## create variable for list of table files
baserecaltablelist=${path2list}'baserecaltablelist.txt'

## create a name variable
## note this name has '.bam' extension included
## e.g. i1-lib001-A01.bam
namewext=`head -n $SGE_TASK_ID $baserecaltablelist | tail -n 1 | cut -f1`

## remove ext from name
## e.g. name=i1-lib001-A01
name=${namewext%'.table'}


#############################
## gatk pre-processing con't
#############################


## apply base quality score recalibration to bams
    ## https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_hellbender_tools_walkers_bqsr_AnalyzeCovariates.php
    ## generates plots to assess the quality of a recalibration

gatk AnalyzeCovariates \
    -bqsr $path2tables$namewext \
    -plots $path2analcovs'AnalyzeCovariates.pdf' \
    -csv $path2analcovs'AnalyzeCovariates.csv'


## Next run gatksomsnv-1-Mutect2-v0.1.0.sh


